name: Get Image Tag
description: |
  Get the image tag for the current commit, either the short hash or the tagged version.
  Requires that the repo be checked out.

outputs:
  image_tag:
    description: The image tag for the current commit
    value: ${{ steps.vars.outputs.image_tag }}

runs:
  using: "composite"
  steps:
    - name: Set env var for tag
      shell: bash
      if: ${{ github.ref_type == 'tag' }}
      run: |
        echo "IMAGE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

    - name: Set env var for commit hash
      shell: bash
      if: ${{ github.ref_type != 'tag' }}
      run: |
        echo "IMAGE_TAG=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - name: set output vars
      shell: bash
      id: vars
      run: |
        echo image_tag=${{ env.IMAGE_TAG }} >> $GITHUB_OUTPUT
